ALTER TABLE "Tour" ADD COLUMN IF NOT EXISTS "category" TEXT;

ALTER TABLE "Guide" ADD COLUMN IF NOT EXISTS "restaurantName" TEXT;
ALTER TABLE "Guide" ADD COLUMN IF NOT EXISTS "gastronomyCategory" TEXT;
ALTER TABLE "Guide" ADD COLUMN IF NOT EXISTS "experienceName" TEXT;
ALTER TABLE "Guide" ADD COLUMN IF NOT EXISTS "gastronomyArea" TEXT;
ALTER TABLE "Guide" ADD COLUMN IF NOT EXISTS "chefTags" TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE "Guide" ADD COLUMN IF NOT EXISTS "menuCourses" JSONB;
ALTER TABLE "Guide" ADD COLUMN IF NOT EXISTS "story" JSONB;
